server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: palaoh
    password: 1234
    url: jdbc:mysql://localhost:3306/nalaolla?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

    # mariaDB
  #    driverClassName: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/DB명?allowMultiQueries=true
  #    username: userid
  #    password: pwd
  #    initial-size: 1
  #    max-active: 3
  #    min-idle: 1
  #    max-idle: 3
  #    max-wait: 30000
  #    test-on-borrow: true
  #    test-on-return: true
  #    test-while-idle: true
  #    time-between-eviction-runs-millis: 30000
  #    validation-query: 'SELECT 1'
  #    validation-query-timeout: 3
  #    validation-interval: 30000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

  h2:
    console:
      enabled: true